<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detail</name>
   <tag></tag>
   <elementGuidId>8714d4a5-ea82-488c-a385-ce0ff134a123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@type='button'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>187d694c-fe9b-4ca0-b116-9df09ede1df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://career.vasdev.co.id/admin/vacancy/VAD-3</value>
      <webElementGuid>35b26388-b105-45f4-b826-3ec59c9a3a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ee68fd4-cd0b-4da3-81ba-fd18535a8489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary</value>
      <webElementGuid>69f72fbd-2de6-4668-8d5c-d44bac61635b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Detail
    </value>
      <webElementGuid>0a18403a-b4c5-4482-a62a-cd7ff45032ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatables&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/div[@class=&quot;btn-group&quot;]/a[@class=&quot;btn btn-outline-primary&quot;]</value>
      <webElementGuid>6ca00b81-ab70-4ad9-8f87-fdd2573762df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@type='button'])[7]</value>
      <webElementGuid>0648a0e1-1674-4792-bca9-4ac6dfcf2a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='datatables']/tbody/tr[3]/td[9]/div/a</value>
      <webElementGuid>8e071f5b-fdc4-413c-8c34-fe3cc007f986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Detail')])[3]</value>
      <webElementGuid>28d2b515-302f-41f1-8516-c93551116654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remote'])[1]/following::a[1]</value>
      <webElementGuid>1fbf85eb-0e83-4362-b1ed-e04e248eb64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End: 29-07-2023'])[1]/following::a[1]</value>
      <webElementGuid>35a3783a-a355-46e0-83e0-8a93c9976c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[3]/preceding::a[1]</value>
      <webElementGuid>beca07c7-2e2d-4bae-80a5-b6cc20ff38c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[3]/preceding::a[2]</value>
      <webElementGuid>55ccaed9-fff5-4dc0-b9c0-0f7f70ecea44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://career.vasdev.co.id/admin/vacancy/VAD-3')]</value>
      <webElementGuid>3ea0ed26-95aa-4bd8-8efc-def309e68f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[9]/div/a</value>
      <webElementGuid>e26a8681-b5ab-4ffa-9330-7a72c63a13aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://career.vasdev.co.id/admin/vacancy/VAD-3' and @type = 'button' and (text() = '
        Detail
    ' or . = '
        Detail
    ')]</value>
      <webElementGuid>9259aeb0-45a5-450d-bdff-3fb2be973dac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
